export const Cursos = [
    {
      id: "1",
      name: "Programação em JavaScript",
      rating: 4.5,
      photo: "imagem1.jpg",
      price: 49.99,
    },
    {
      id: "2",
      name: "Design Gráfico",
      ownerId: "456",
      rating: 4.2,
      numberOfRatings: 150,
      photo: "imagem2.jpg",
      enrollmentsNumber: 800,
      price: 39.99,
    },
    {
      id: "3",
      name: "Marketing Digital",
      ownerId: "789",
      rating: 4.7,
      numberOfRatings: 300,
      photo: "imagem3.jpg",
      enrollmentsNumber: 1200,
      price: 59.99,
    },
    {
      id: "4",
      name: "Fotografia",
      ownerId: "101",
      rating: 4.4,
      numberOfRatings: 180,
      photo: "imagem4.jpg",
      enrollmentsNumber: 700,
      price: 44.99,
    },
    {
      id: "5",
      name: "Marketing de Mídia Social",
      ownerId: "202",
      rating: 4.6,
      numberOfRatings: 250,
      photo: "imagem5.jpg",
      enrollmentsNumber: 900,
      price: 54.99,
    },
    {
      id: "6",
      name: "Desenvolvimento Web",
      ownerId: "303",
      rating: 4.8,
      numberOfRatings: 350,
      photo: "imagem6.jpg",
      enrollmentsNumber: 1500,
      price: 69.99,
    },
    {
      id: "7",
      name: "Inglês Avançado",
      ownerId: "404",
      rating: 4.9,
      numberOfRatings: 400,
      photo: "imagem7.jpg",
      enrollmentsNumber: 2000,
      price: 79.99,
    },
    {
      id: "8",
      name: "Ciência de Dados",
      ownerId: "505",
      rating: 4.7,
      numberOfRatings: 320,
      photo: "imagem8.jpg",
      enrollmentsNumber: 1300,
      price: 64.99,
    },
    {
      id: "9",
      name: "Culinária Italiana",
      ownerId: "606",
      rating: 4.3,
      numberOfRatings: 170,
      photo: "imagem9.jpg",
      enrollmentsNumber: 600,
      price: 49.99,
    },
    {
      id: "10",
      name: "Yoga e Meditação",
      ownerId: "707",
      rating: 4.6,
      numberOfRatings: 220,
      photo: "imagem10.jpg",
      enrollmentsNumber: 850,
      price: 59.99,
    },
    {
     id: "11",
     name: "Aprendendo React",
     ownerId: "808",
     rating: 4.2,
     numberOfRatings: 190,
     photo: "imagem11.jpg",
     enrollmentsNumber: 850,
     price: 54.99,
   },
   {
     id: "12",
     name: "Ilustração Digital",
     ownerId: "909",
     rating: 4.6,
     numberOfRatings: 240,
     photo: "imagem12.jpg",
     enrollmentsNumber: 950,
     price: 49.99,
   },
   {
     id: "13",
     name: "Programação em Python",
     ownerId: "1010",
     rating: 4.8,
     numberOfRatings: 380,
     photo: "imagem13.jpg",
     enrollmentsNumber: 1600,
     price: 69.99,
   },
   {
     id: "14",
     name: "Fotografia de Paisagem",
     ownerId: "1111",
     rating: 4.4,
     numberOfRatings: 210,
     photo: "imagem14.jpg",
     enrollmentsNumber: 720,
     price: 44.99,
   },
   {
     id: "15",
     name: "Gestão de Redes Sociais",
     ownerId: "1212",
     rating: 4.7,
     numberOfRatings: 290,
     photo: "imagem15.jpg",
     enrollmentsNumber: 1100,
     price: 59.99,
   },
   {
     id: "16",
     name: "Desenvolvimento Android",
     ownerId: "1313",
     rating: 4.9,
     numberOfRatings: 420,
     photo: "imagem16.jpg",
     enrollmentsNumber: 1800,
     price: 79.99,
   },
   {
     id: "17",
     name: "Introdução à Inteligência Artificial",
     ownerId: "1414",
     rating: 4.7,
     numberOfRatings: 330,
     photo: "imagem17.jpg",
     enrollmentsNumber: 1400,
     price: 64.99,
   },
   {
     id: "18",
     name: "Culinária Japonesa",
     ownerId: "1515",
     rating: 4.3,
     numberOfRatings: 160,
     photo: "imagem18.jpg",
     enrollmentsNumber: 550,
     price: 49.99,
   },
   {
     id: "19",
     name: "Meditação Guiada",
     ownerId: "1616",
     rating: 4.6,
     numberOfRatings: 230,
     photo: "imagem19.jpg",
     enrollmentsNumber: 880,
     price: 59.99,
   },
   {
     id: "20",
     name: "Espanhol para Iniciantes",
     ownerId: "1717",
     rating: 4.5,
     numberOfRatings: 210,
     photo: "imagem20.jpg",
     enrollmentsNumber: 780,
     price: 39.99,
   },
 ];

 export const Modulos = [
    {
      id: "1",
      name: "Programação em JavaScript",
      description: "esse curso ensinara voce a programar em javascript",
      createdAt: "11/09/2023",
      course: "Curso de Javascript",
      staff: "prof 1"
    },
    {
        id: "2",
        name: "Desenvolvimento Web",
        description: "Aprenda a criar aplicativos da web incríveis",
        createdAt: "11/09/2023",
        course: "Curso de Desing",
        staff: "prof 2"
      },
      {
        id: "3",
        name: "Introdução à Inteligência Artificial",
        description: "Explore os conceitos básicos da IA",
        createdAt: "11/09/2023",
        course: "Curso de Programação",
        staff: "prof 3"
      },
      {
        id: "4",
        name: "Aprendizado de Máquina Avançado",
        description: "Domine algoritmos de aprendizado de máquina avançados",
        createdAt: "11/09/2023",
        course: "Curso de Programaçao",
        staff: "prof 3"
      },
      {
        id: "5",
        name: "Ciência de Dados para Iniciantes",
        description: "Inicie sua jornada na análise de dados",
        createdAt: "11/09/2023",
        course: "Curso de Programaçao",
        staff: "prof 3"
      },
      {
        id: "6",
        name: "Desenvolvimento de Aplicativos Móveis",
        description: "Aprenda a criar aplicativos móveis para iOS e Android",
        createdAt: "11/09/2023",
        course: "Curso Mobile",
        staff: "prof 4"
      },
      {
        id: "7",
        name: "Web Design Responsivo",
        description: "Crie sites que se adaptam a dispositivos diferentes",
        createdAt: "11/09/2023",
        course: "Curso de Desing",
        staff: "prof 2"
      },
      {
        id: "8",
        name: "Programação em Python",
        description: "Domine uma das linguagens de programação mais populares",
        createdAt: "11/09/2023",
        course: "Curso de Python",
        staff: "prof 5"
      },
      {
        id: "9",
        name: "Desenvolvimento de Jogos",
        description: "Crie seus próprios jogos emocionantes",
        createdAt: "11/09/2023",
        course: "Curso de Games",
        staff: "prof 6"
      },
      {
        id: "10",
        name: "Administração de Bancos de Dados",
        description: "Aprenda a gerenciar dados com eficiência",
        createdAt: "11/09/2023",
        course: "Curso BD",
        staff: "prof 7"
      },
 ]